### ISSUE TITLE
digris-edi2edi - Segmentation fault

### ISSUE THREAD

**Issue by chicco64** [digris/digris-edi-zmq-bridge#1] opened 2024-07-18 09:11 UTC
With curiosity, I carried out a test on the new application in question but I encountered a blocking error when started:
DIGRIS-EDI2EDI v0.6.0 starting up
Developed for Opendigitalradio by digris: https://www.digris.ch

2024-07-18Z09:07:11       Setting up EDI2EDI with delay 300 ms.
2024-07-18Z09:07:11       EDI inputs
2024-07-18Z09:07:11        my ip:my port enabled
2024-07-18Z09:07:11       EDI Output
2024-07-18Z09:07:11        verbose     0
2024-07-18Z09:07:11        UDP to 127.0.0.1:my port
2024-07-18Z09:07:11         source port 12000
2024-07-18Z09:07:11       ZMQ output: disabled
2024-07-18Z09:07:11       Initialise next_pseq to 61565
2024-07-18Z09:07:11       EDI AF Packet initial sequence number: 61565
Segmentation fault

I point out that with the previous edi2edi the reception was perfect.
Any suggestions ? many thanks

**Comment by YoannQueret** [comment] 2024-07-18 16:21
@chicco64 Can you show the command line with the options you use?

**Comment by chicco64** [comment] 2024-07-18 16:32
Sure....

# odr-edi2edi -c 192.168.1.211:13000 -w 500 -d 127.0.0.1 -p 3123 -s 12000

ODR-EDI2EDI v0.4.0 starting up
      Setting up EDI2EDI with delay 500 ms. Will not drop late packets
      EDI Output
       verbose     0
       UDP to 127.0.0.1:3123
        source port 12000
      Connecting to TCP 192.168.1.211:13000
      Initialise next_pseq to 49961
      EDI AF Packet initial sequence number: 49961
      Buffering time statistics [milliseconds]: min: 2471.59 max: 2472.24 mean: 2471.93 stdev: 0.196665 late: 0 of 11 (0%) Frame 0 TS 0
      Buffering time statistics [milliseconds]: min: 2471.56 max: 2472.5 mean: 2471.93 stdev: 0.176761 late: 0 of 250 (0%) Frame 0 TS 0
      Buffering time statistics [milliseconds]: min: 2471.51 max: 2472.34 mean: 2471.91 stdev: 0.172403 late: 0 of 250 (0%) Frame 0 TS 0
Work!

but....

# digrisdr-edi2edi -c 192.168.1.211:13000 -w 500 -d 127.0.0.1 -p 3123 -s 12000

DIGRIS-EDI2EDI v0.6.0 starting up
Developed for Opendigitalradio by digris: https://www.digris.ch

2024-07-18Z16:28:39       Setting up EDI2EDI with delay 500 ms.
2024-07-18Z16:28:39       EDI inputs
2024-07-18Z16:28:39        192.168.1.211:13000 enabled
2024-07-18Z16:28:39       EDI Output
2024-07-18Z16:28:39        verbose     0
2024-07-18Z16:28:39        UDP to 127.0.0.1:3123
2024-07-18Z16:28:39         source port 12000
2024-07-18Z16:28:39       ZMQ output: disabled
2024-07-18Z16:28:39       Initialise next_pseq to 51125
2024-07-18Z16:28:39       EDI AF Packet initial sequence number: 51125
Segmentation fault

Dont'work !

where is the error?

**Comment by YoannQueret** [comment] 2024-07-18 16:56
can you try with a negative value for -w parameters

**Comment by chicco64** [comment] 2024-07-18 17:00
is the same, don't work

**Comment by mpbraendli** [comment] 2024-07-18 20:26
Thanks @chicco64 for letting us know, and @YoannQueret clarifications. The issue is fixed in `next`. Please reopen the issue if it isn't working for you.

**Closed as completed by mpbraendli** 2024-07-18 20:26 UTC
Labels: bug
